KXHIGHNY-25DEC04-B41.5:
  api:
    market_ticker: KXHIGHNY-25DEC04-B41.5
    trade_side: "yes"
  market_maker:
    max_position: 50
    order_expiration: 28800 # 8 hours
    gamma: 0.1
    k: 1.5
    sigma: 0.001
    T: 28800 # 8 hours
    min_spread: 0.0
    position_limit_buffer: 0.5
    inventory_skew_factor: 0.001
    max_order_size: 20
  dt: 2.0


KXHIGHNY-25DEC04-B39.5:
  api:
    market_ticker: KXHIGHNY-25DEC04-B39.5
    trade_side: "yes"
  market_maker:
    max_position: 100
    order_expiration: 28800 # 8 hours
    gamma: 0.1
    k: 1.5
    sigma: 0.001
    T: 28800 # 8 hours
    min_spread: 0.0
    position_limit_buffer: 0.1
    inventory_skew_factor: 0.001
    max_order_size: 20
  dt: 2.0
